# Imatge base
FROM node:18

# Crear directori de treball dins del contenidor
WORKDIR /app

# Copiar els fitxers de dependències
COPY package*.json ./

# Instal·lar les dependències del projecte
RUN npm install

# Copiar el codi font
COPY . .

# Exposar el port 3000
EXPOSE 3000

# Comanda per iniciar l'aplicació
CMD ["npm", "start"]
